namespace PungentFunk.Utilities.Editor.Theme
{
#if UNITY_EDITOR
    using System.Collections.Generic;
    using System.Globalization;
    using System.Text;
    using UnityEditor;
    using UnityEngine;

    public static class PungentEditorSkinUssGenerator
    {
        public static string BuildUss(PungentEditorSkinProfile profile, IEnumerable<PungentEditorStyleOverride> overrides, bool disabled)
        {
            var builder = new StringBuilder(8192);
            builder.AppendLine("/* <auto-generated> PungentFunk experimental Unity Editor skin bridge. */");
            builder.AppendLine("/* This file is generated from the Appearance Lab. Disable the bridge to restore an empty extension sheet. */");
            builder.AppendLine("/* It uses Unity editor USS extension selectors only; it does not patch editor resources or wrap IMGUI callbacks. */");
            builder.AppendLine("/* Raw preset readability should be judged with the bridge disabled. The bridge is a broader editor-theme preview and can shift apparent contrast inside the Appearance Lab itself. */");
            builder.AppendLine("/* Some Unity internals, especially script/asset preview implementations that stay in IMGUI or hidden native containers, may not expose stable USS hooks in every version. */");
            builder.AppendLine("/* Hierarchy note: if the left gutter/indent strip ignores all hierarchy USS selectors, that strip is likely drawn by Unity's IMGUI/native TreeView layer and needs session GUIStyle bridge coverage rather than generated USS. */");
            builder.AppendLine();

            if (disabled)
            {
                builder.AppendLine("/* Bridge disabled. No overrides emitted. */");
                return builder.ToString();
            }

            if (profile != null)
                builder.AppendLine($"/* Profile: {EscapeComment(profile.displayName)} | Base skin: {(EditorGUIUtility.isProSkin ? "Dark" : "Light")} */");

            int count = 0;
            foreach (PungentEditorStyleOverride item in overrides)
            {
                if (!item.EnabledByDefault || string.IsNullOrWhiteSpace(item.Selector))
                    continue;

                string property = ToUssProperty(item.Property);
                string value = ToUssValue(item);
                if (string.IsNullOrEmpty(property) || string.IsNullOrEmpty(value))
                    continue;

                builder.AppendLine($"{item.Selector} {{ {property}: {value}; }}");
                count++;
            }

            AppendSupplementalBlocks(builder);
            builder.AppendLine();
            builder.AppendLine($"/* Selectors emitted: {count} */");
            return builder.ToString();
        }

        private static string ToUssProperty(PungentEditorSkinProperty property)
        {
            switch (property)
            {
                case PungentEditorSkinProperty.Color:
                    return "color";
                case PungentEditorSkinProperty.BorderColor:
                    return "border-color";
                case PungentEditorSkinProperty.BorderWidth:
                    return "border-width";
                case PungentEditorSkinProperty.BorderRadius:
                    return "border-radius";
                case PungentEditorSkinProperty.UnityFont:
                    return "-unity-font";
                case PungentEditorSkinProperty.FontSize:
                    return "font-size";
                case PungentEditorSkinProperty.ImageTintColor:
                    return "-unity-background-image-tint-color";
                default:
                    return "background-color";
            }
        }

        private static string ToUssValue(PungentEditorStyleOverride item)
        {
            switch (item.Property)
            {
                case PungentEditorSkinProperty.BorderWidth:
                    return Mathf.Max(0, UtilityWindowTheme.PanelBorderWidth).ToString(CultureInfo.InvariantCulture) + "px";
                case PungentEditorSkinProperty.BorderRadius:
                    return Mathf.Max(0, UtilityWindowTheme.PanelCornerRadius).ToString(CultureInfo.InvariantCulture) + "px";
                case PungentEditorSkinProperty.UnityFont:
                    return TryGetFontUrl(item.ThemeRole);
                case PungentEditorSkinProperty.FontSize:
                    return Mathf.RoundToInt(12f * UtilityWindowTheme.TextScale).ToString(CultureInfo.InvariantCulture) + "px";
                case PungentEditorSkinProperty.ImageTintColor:
                    return ToRgba(WithAlpha(UtilityWindowTheme.GetColor(item.ThemeRole), item.AlphaMultiplier));
                default:
                    return ToRgba(WithAlpha(UtilityWindowTheme.GetColor(item.ThemeRole), item.AlphaMultiplier));
            }
        }

        private static void AppendSupplementalBlocks(StringBuilder builder)
        {
            builder.AppendLine();
            builder.AppendLine("/* Supplemental broad UI Toolkit selectors. Some Unity versions ignore some of these classes. */");
            builder.AppendLine($".unity-label, .unity-button, .unity-toggle, .unity-foldout, .unity-foldout__text, .unity-property-field, .unity-object-field {{ color: {ToRgba(UtilityWindowTheme.CardText)}; }}");
            builder.AppendLine($".unity-toolbar, .unity-main-toolbar, .unity-editor-toolbar, .unity-toolbar-menu, .unity-toolbar__contents, .unity-toolbar__left, .unity-toolbar__center, .unity-toolbar__right, .AppToolbar, .PreToolbar, .Toolbar, .ToolbarZone, .ToolbarLeftAlign, .ToolbarCenterAlign, .ToolbarRightAlign {{ background-color: {ToRgba(WithAlpha(UtilityWindowTheme.HeaderTint, 0.98f))}; }}");
            builder.AppendLine($".unity-scroll-view, .unity-list-view, .unity-tree-view, .SceneHierarchyWindow, .unity-scene-hierarchy, .unity-scene-hierarchy-window, .unity-scene-hierarchy-window__tree-view, .unity-scene-hierarchy__tree-view, .unity-scene-hierarchy-window__list-view, .unity-inspector-main-container, .unity-inspector-root, .unity-inspector-editors-list {{ background-color: {ToRgba(WithAlpha(UtilityWindowTheme.HeaderTint, 0.32f))}; }}");
            builder.AppendLine($".unity-tree-view__item, .unity-tree-view__item-content, .unity-scene-hierarchy-item, .unity-scene-hierarchy-item__label {{ color: {ToRgba(UtilityWindowTheme.CardText)}; }}");
            builder.AppendLine($".unity-tree-view__item-indent, .unity-tree-view__item-indentation, .unity-tree-view__item-toggle {{ background-color: {ToRgba(WithAlpha(UtilityWindowTheme.HeaderTint, 0.28f))}; -unity-background-image-tint-color: {ToRgba(WithAlpha(UtilityWindowTheme.Cyan, 0.85f))}; }}");
            AppendHierarchyHardeningBlock(builder);
            builder.AppendLine($".unity-tree-view__item--selected, .unity-collection-view__item--selected {{ background-color: {ToRgba(WithAlpha(UtilityWindowTheme.Blue, 0.42f))}; color: {ToRgba(UtilityWindowTheme.TitleText)}; }}");
            builder.AppendLine($".unity-inspector-titlebar, .dockHeader, .dragtab {{ background-color: {ToRgba(WithAlpha(UtilityWindowTheme.HeaderTint, 0.78f))}; color: {ToRgba(UtilityWindowTheme.TitleText)}; }}");
            builder.AppendLine($".unity-inspector-titlebar-label, .unity-tab__label, .dragtab-label {{ color: {ToRgba(UtilityWindowTheme.TitleText)}; }}");
            builder.AppendLine($".unity-base-field__label, .unity-property-field__label {{ color: {ToRgba(UtilityWindowTheme.SubtitleText)}; }}");
            builder.AppendLine($".unity-base-field__input, .unity-text-field__input, .unity-object-field__input {{ color: {ToRgba(UtilityWindowTheme.CardText)}; background-color: {ToRgba(WithAlpha(UtilityWindowTheme.Neutral, 0.16f))}; border-color: {ToRgba(WithAlpha(UtilityWindowTheme.Neutral, UtilityWindowTheme.PanelBorderOpacity))}; border-width: {UtilityWindowTheme.PanelBorderWidth}px; border-radius: {UtilityWindowTheme.PanelCornerRadius}px; }}");
            AppendInspectorCoverageBlock(builder);
            AppendProjectCoverageBlock(builder);
            AppendConsoleCoverageBlock(builder);
            AppendSceneViewCoverageBlock(builder);
            AppendTabChromeCoverageBlock(builder);
            builder.AppendLine($".ScriptInspector, .ScriptText, .ScriptTextNumber, .ScriptTextPreprocessor, .unity-script-inspector, .unity-script-inspector__preview, .unity-inspector-preview, .unity-code-preview {{ color: {ToRgba(UtilityWindowTheme.PathText)}; background-color: {ToRgba(WithAlpha(UtilityWindowTheme.HeaderTint, 0.28f))}; }}");
            builder.AppendLine("/* Script preview backgrounds are only styled when Unity exposes preview panels through these classes; some MonoScript/native preview hosts remain partially inaccessible. */");
            builder.AppendLine($".ScriptTextNumber {{ color: {ToRgba(UtilityWindowTheme.MutedText)}; }}");
            builder.AppendLine($".unity-button:hover, .unity-toolbar-button:hover, .ToolbarButton:hover {{ background-color: {ToRgba(WithAlpha(UtilityWindowTheme.Blue, 0.28f))}; }}");
            builder.AppendLine($".unity-button:checked, .unity-toolbar-button:checked, .ToolbarButton:checked {{ background-color: {ToRgba(WithAlpha(UtilityWindowTheme.Blue, 0.42f))}; }}");
            builder.AppendLine($".unity-help-box {{ color: {ToRgba(UtilityWindowTheme.CardText)}; border-color: {ToRgba(WithAlpha(UtilityWindowTheme.Amber, 0.42f))}; background-color: {ToRgba(WithAlpha(UtilityWindowTheme.Neutral, 0.18f))}; }}");
            builder.AppendLine($".unity-icon, .unity-image, .unity-object-field__selector, .unity-foldout__checkmark, .unity-inspector-titlebar-icon {{ -unity-background-image-tint-color: {ToRgba(WithAlpha(UtilityWindowTheme.Cyan, 0.90f))}; }}");

            builder.AppendLine("/* Font role mapping: controlled from the Editor Style Explorer. */");
            AppendMappedFontBlock(builder, PungentEditorTextTarget.HierarchyItems);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.HierarchyGutter);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.InspectorHeaders);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.InspectorLabels);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.PropertyFields);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.ToolbarButtons);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.Tabs);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.ConsoleRows);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.ProjectItems);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.CodePreview);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.PathLabels);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.Links);
            AppendMappedFontBlock(builder, PungentEditorTextTarget.MutedHelpText);
        }


        private static void AppendHierarchyHardeningBlock(StringBuilder builder)
        {
            Color root = UtilityWindowTheme.HeaderTint;
            root.a = 1f;

            Color backing = Color.Lerp(UtilityWindowTheme.HeaderTint, Color.black, EditorGUIUtility.isProSkin ? 0.08f : 0.02f);
            backing.a = 1f;

            Color rail = Color.Lerp(UtilityWindowTheme.HeaderTint, UtilityWindowTheme.Blue, EditorGUIUtility.isProSkin ? 0.14f : 0.08f);
            rail.a = 1f;

            Color row = WithAlpha(Color.Lerp(UtilityWindowTheme.HeaderTint, UtilityWindowTheme.Blue, 0.08f), EditorGUIUtility.isProSkin ? 0.42f : 0.22f);
            Color hover = WithAlpha(UtilityWindowTheme.Blue, EditorGUIUtility.isProSkin ? 0.30f : 0.16f);
            Color selected = WithAlpha(UtilityWindowTheme.Blue, EditorGUIUtility.isProSkin ? 0.58f : 0.34f);
            Color selectedRail = Color.Lerp(UtilityWindowTheme.HeaderTint, UtilityWindowTheme.Blue, EditorGUIUtility.isProSkin ? 0.42f : 0.26f);
            selectedRail.a = 1f;

            Color text = UtilityWindowTheme.CardText;
            Color title = UtilityWindowTheme.TitleText;
            Color accent = WithAlpha(UtilityWindowTheme.Cyan, 0.96f);
            Color border = WithAlpha(UtilityWindowTheme.Neutral, EditorGUIUtility.isProSkin ? 0.42f : 0.24f);

            string hierarchyRoots =
                ".SceneHierarchyWindow, " +
                "#SceneHierarchyWindow, " +
                ".unity-scene-hierarchy-window, " +
                ".scene-hierarchy-window, " +
                ".unity-scene-hierarchy, " +
                ".SceneHierarchyWindow .unity-imgui-container, " +
                ".unity-scene-hierarchy-window .unity-imgui-container, " +
                ".scene-hierarchy-window .unity-imgui-container, " +
                ".unity-scene-hierarchy .unity-imgui-container";

            string hierarchyBackings =
                ".SceneHierarchyWindow .unity-scroll-view, " +
                ".SceneHierarchyWindow .unity-scroll-view__content-and-vertical-scroll-container, " +
                ".SceneHierarchyWindow .unity-scroll-view__content-viewport, " +
                ".SceneHierarchyWindow .unity-scroll-view__content-container, " +
                ".SceneHierarchyWindow .unity-collection-view, " +
                ".SceneHierarchyWindow .unity-collection-view__scroll-view, " +
                ".SceneHierarchyWindow .unity-collection-view__content-viewport, " +
                ".SceneHierarchyWindow .unity-collection-view__content-container, " +
                ".SceneHierarchyWindow .unity-list-view, " +
                ".SceneHierarchyWindow .unity-list-view__content-viewport, " +
                ".SceneHierarchyWindow .unity-list-view__content-container, " +
                ".SceneHierarchyWindow .unity-tree-view, " +
                ".SceneHierarchyWindow .unity-tree-view__container, " +
                ".SceneHierarchyWindow .unity-tree-view__content-viewport, " +
                ".SceneHierarchyWindow .unity-tree-view__content-container, " +
                ".SceneHierarchyWindow .unity-base-tree-view, " +
                ".SceneHierarchyWindow .unity-base-tree-view__container, " +
                ".SceneHierarchyWindow .unity-base-tree-view__content-viewport, " +
                ".SceneHierarchyWindow .unity-base-tree-view__content-container, " +
                ".unity-scene-hierarchy-window .unity-scroll-view, " +
                ".unity-scene-hierarchy-window .unity-scroll-view__content-and-vertical-scroll-container, " +
                ".unity-scene-hierarchy-window .unity-scroll-view__content-viewport, " +
                ".unity-scene-hierarchy-window .unity-scroll-view__content-container, " +
                ".unity-scene-hierarchy-window .unity-collection-view, " +
                ".unity-scene-hierarchy-window .unity-collection-view__scroll-view, " +
                ".unity-scene-hierarchy-window .unity-collection-view__content-viewport, " +
                ".unity-scene-hierarchy-window .unity-collection-view__content-container, " +
                ".unity-scene-hierarchy-window .unity-list-view, " +
                ".unity-scene-hierarchy-window .unity-list-view__content-viewport, " +
                ".unity-scene-hierarchy-window .unity-list-view__content-container, " +
                ".unity-scene-hierarchy-window .unity-tree-view, " +
                ".unity-scene-hierarchy-window .unity-tree-view__container, " +
                ".unity-scene-hierarchy-window .unity-tree-view__content-viewport, " +
                ".unity-scene-hierarchy-window .unity-tree-view__content-container, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__container, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__content-viewport, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__content-container, " +
                ".unity-scene-hierarchy-window__tree-view, " +
                ".unity-scene-hierarchy-window__tree-view-container, " +
                ".unity-scene-hierarchy-window__list-view, " +
                ".unity-scene-hierarchy-window__content-container, " +
                ".unity-scene-hierarchy-window__container, " +
                ".unity-scene-hierarchy-window__scroll-view, " +
                ".unity-scene-hierarchy__tree-view";

            string hierarchyRows =
                ".SceneHierarchyWindow .unity-collection-view__item, " +
                ".SceneHierarchyWindow .unity-list-view__item, " +
                ".SceneHierarchyWindow .unity-tree-view__item, " +
                ".SceneHierarchyWindow .unity-tree-view__item > *, " +
                ".SceneHierarchyWindow .unity-tree-view__item-content, " +
                ".SceneHierarchyWindow .unity-tree-view__item-content-container, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item > *, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item-content, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item-content-container, " +
                ".unity-scene-hierarchy-window .unity-collection-view__item, " +
                ".unity-scene-hierarchy-window .unity-list-view__item, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item > *, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item-content, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item-content-container, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item > *, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item-content, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item-content-container, " +
                ".unity-scene-hierarchy-item, " +
                ".unity-scene-hierarchy-item__label";

            string hierarchyRails =
                ".SceneHierarchyWindow .unity-tree-view__item-indent, " +
                ".SceneHierarchyWindow .unity-tree-view__item-indentation, " +
                ".SceneHierarchyWindow .unity-tree-view__item-indent-container, " +
                ".SceneHierarchyWindow .unity-tree-view__item-toggle, " +
                ".SceneHierarchyWindow .unity-tree-view__item-toggle > *, " +
                ".SceneHierarchyWindow .unity-tree-view__item-toggle .unity-toggle__input, " +
                ".SceneHierarchyWindow .unity-tree-view__item-toggle .unity-toggle__checkmark, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item-indent, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item-indentation, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item-indent-container, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item-toggle, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item-toggle > *, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item-toggle .unity-toggle__input, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item-toggle .unity-toggle__checkmark, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item-indent, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item-indentation, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item-indent-container, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item-toggle, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item-toggle > *, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item-toggle .unity-toggle__input, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item-toggle .unity-toggle__checkmark, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item-indent, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item-indentation, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item-indent-container, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item-toggle, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item-toggle > *, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item-toggle .unity-toggle__input, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item-toggle .unity-toggle__checkmark, " +
                ".unity-scene-hierarchy-window .unity-foldout__input, " +
                ".unity-scene-hierarchy-window .unity-foldout__checkmark";

            string hierarchyHoverRows =
                ".SceneHierarchyWindow .unity-collection-view__item:hover, " +
                ".SceneHierarchyWindow .unity-list-view__item:hover, " +
                ".SceneHierarchyWindow .unity-tree-view__item:hover, " +
                ".SceneHierarchyWindow .unity-tree-view__item:hover > *, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item:hover, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item:hover > *, " +
                ".unity-scene-hierarchy-window .unity-collection-view__item:hover, " +
                ".unity-scene-hierarchy-window .unity-list-view__item:hover, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item:hover, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item:hover > *, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item:hover, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item:hover > *";

            string hierarchySelectedRows =
                ".SceneHierarchyWindow .unity-collection-view__item--selected, " +
                ".SceneHierarchyWindow .unity-list-view__item--selected, " +
                ".SceneHierarchyWindow .unity-tree-view__item--selected, " +
                ".SceneHierarchyWindow .unity-tree-view__item--selected > *, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item--selected, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item--selected > *, " +
                ".unity-scene-hierarchy-window .unity-collection-view__item--selected, " +
                ".unity-scene-hierarchy-window .unity-list-view__item--selected, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item--selected, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item--selected > *, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item--selected, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item--selected > *, " +
                ".unity-tree-view__item--selected, " +
                ".unity-base-tree-view__item--selected, " +
                ".unity-collection-view__item--selected, " +
                ".unity-list-view__item--selected";

            string hierarchySelectedRails =
                ".SceneHierarchyWindow .unity-tree-view__item--selected .unity-tree-view__item-indent, " +
                ".SceneHierarchyWindow .unity-tree-view__item--selected .unity-tree-view__item-indentation, " +
                ".SceneHierarchyWindow .unity-tree-view__item--selected .unity-tree-view__item-indent-container, " +
                ".SceneHierarchyWindow .unity-tree-view__item--selected .unity-tree-view__item-toggle, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item--selected .unity-base-tree-view__item-indent, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item--selected .unity-base-tree-view__item-indentation, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item--selected .unity-base-tree-view__item-indent-container, " +
                ".SceneHierarchyWindow .unity-base-tree-view__item--selected .unity-base-tree-view__item-toggle, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item--selected .unity-tree-view__item-indent, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item--selected .unity-tree-view__item-indentation, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item--selected .unity-tree-view__item-indent-container, " +
                ".unity-scene-hierarchy-window .unity-tree-view__item--selected .unity-tree-view__item-toggle, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item--selected .unity-base-tree-view__item-indent, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item--selected .unity-base-tree-view__item-indentation, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item--selected .unity-base-tree-view__item-indent-container, " +
                ".unity-scene-hierarchy-window .unity-base-tree-view__item--selected .unity-base-tree-view__item-toggle";

            builder.AppendLine("/* Hierarchy hardening: focused coverage for Scene Hierarchy root, backings, BaseTreeView/TreeView rails, foldout/toggle rails, rows, hover, and selection states. */");
            builder.AppendLine("/* The root/backing/rail colours are intentionally opaque. Semi-transparent hierarchy rails can leave Unity's native grey gutter visible underneath. */");
            builder.AppendLine("/* If the absolute far-left hierarchy strip still ignores this block, that strip is being drawn by Unity's native IMGUI TreeView in this editor version and needs the reversible GUIStyle fallback instead of more USS selectors. */");

            builder.AppendLine($"{hierarchyRoots} {{ background-color: {ToRgba(root)}; }}");
            builder.AppendLine($"{hierarchyBackings} {{ background-color: {ToRgba(backing)}; border-color: {ToRgba(border)}; }}");
            builder.AppendLine($"{hierarchyRows} {{ background-color: {ToRgba(row)}; color: {ToRgba(text)}; }}");
            builder.AppendLine($"{hierarchyRails} {{ background-color: {ToRgba(rail)}; -unity-background-image-tint-color: {ToRgba(accent)}; border-color: {ToRgba(border)}; }}");
            builder.AppendLine($"{hierarchyHoverRows} {{ background-color: {ToRgba(hover)}; color: {ToRgba(title)}; -unity-background-image-tint-color: {ToRgba(accent)}; }}");
            builder.AppendLine($"{hierarchySelectedRows} {{ background-color: {ToRgba(selected)}; color: {ToRgba(title)}; -unity-background-image-tint-color: {ToRgba(accent)}; }}");
            builder.AppendLine($"{hierarchySelectedRails} {{ background-color: {ToRgba(selectedRail)}; color: {ToRgba(title)}; -unity-background-image-tint-color: {ToRgba(accent)}; }}");
        }

        private static void AppendInspectorCoverageBlock(StringBuilder builder)
        {
            Color inspectorRoot = WithAlpha(UtilityWindowTheme.HeaderTint, EditorGUIUtility.isProSkin ? 0.34f : 0.12f);
            Color inspectorPanel = WithAlpha(UtilityWindowTheme.Neutral, EditorGUIUtility.isProSkin ? 0.18f : 0.10f);
            Color header = WithAlpha(UtilityWindowTheme.HeaderTint, EditorGUIUtility.isProSkin ? 0.82f : 0.28f);
            Color objectRow = WithAlpha(UtilityWindowTheme.Blue, EditorGUIUtility.isProSkin ? 0.12f : 0.08f);

            builder.AppendLine("/* Inspector coverage: component headers, object header panel, mixed content blocks, and object field rows. */");
            builder.AppendLine($".unity-inspector-root, .unity-inspector-main-container, .unity-inspector-editors-list, .InspectorWindow, .inspector-window {{ background-color: {ToRgba(inspectorRoot)}; }}");
            builder.AppendLine($".unity-inspector-editor, .unity-inspector-element, .unity-property-field, .unity-property-field > *, .unity-object-field, .unity-object-field > *, .unity-inspector-preview, .unity-script-inspector, .unity-script-inspector__preview, .unity-code-preview {{ background-color: {ToRgba(inspectorPanel)}; }}");
            builder.AppendLine($".unity-inspector-titlebar, .unity-inspector-element__header, .unity-inspector-editor-header, .unity-object-header, .unity-object-header__content, .unity-object-header__title, .unity-component-header {{ background-color: {ToRgba(header)}; color: {ToRgba(UtilityWindowTheme.TitleText)}; }}");
            builder.AppendLine($".unity-object-field, .unity-object-field__input, .unity-object-field__selector, .unity-property-field__input, .unity-base-field__aligned, .unity-base-field__inspector-field {{ background-color: {ToRgba(objectRow)}; color: {ToRgba(UtilityWindowTheme.CardText)}; }}");
        }

        private static void AppendProjectCoverageBlock(StringBuilder builder)
        {
            Color toolbar = WithAlpha(UtilityWindowTheme.HeaderTint, EditorGUIUtility.isProSkin ? 0.88f : 0.24f);
            Color preview = WithAlpha(UtilityWindowTheme.Neutral, EditorGUIUtility.isProSkin ? 0.20f : 0.10f);
            Color toggle = WithAlpha(UtilityWindowTheme.Blue, EditorGUIUtility.isProSkin ? 0.20f : 0.12f);

            builder.AppendLine("/* Project browser coverage: top/bottom strips, toolbar toggles, and asset preview/detail panels. */");
            builder.AppendLine($".ProjectBrowserTopBarBg, .ProjectBrowserBottomBarBg, .project-browser-toolbar, .project-browser-bottom-bar, .unity-project-browser-toolbar {{ background-color: {ToRgba(toolbar)}; }}");
            builder.AppendLine($".ProjectBrowserIconAreaBg, .ProjectBrowserGrid, .project-browser-preview, .project-browser-preview-area, .project-browser-details, .unity-project-browser-preview, .unity-project-browser-details {{ background-color: {ToRgba(preview)}; color: {ToRgba(UtilityWindowTheme.CardText)}; }}");
            builder.AppendLine($".project-browser-toggle, .project-browser-bottom-toggle, .unity-project-browser-toggle, .unity-project-browser-toolbar .unity-toggle, .unity-project-browser-toolbar .unity-toolbar-button {{ background-color: {ToRgba(toggle)}; color: {ToRgba(UtilityWindowTheme.CardText)}; }}");
        }

        private static void AppendConsoleCoverageBlock(StringBuilder builder)
        {
            Color toolbar = WithAlpha(UtilityWindowTheme.HeaderTint, EditorGUIUtility.isProSkin ? 0.88f : 0.24f);
            Color row = WithAlpha(UtilityWindowTheme.Neutral, EditorGUIUtility.isProSkin ? 0.16f : 0.08f);
            Color selected = WithAlpha(UtilityWindowTheme.Blue, EditorGUIUtility.isProSkin ? 0.42f : 0.22f);

            builder.AppendLine("/* Console coverage: toolbar toggles, filter buttons, and row backgrounds where Unity exposes USS hooks. */");
            builder.AppendLine($".CN Toolbar, .console-toolbar, .ConsoleWindow .unity-toolbar, .unity-console-toolbar, .unity-console-toolbar__container {{ background-color: {ToRgba(toolbar)}; color: {ToRgba(UtilityWindowTheme.CardText)}; }}");
            builder.AppendLine($".CN EntryBackEven, .CN EntryBackOdd, .unity-console-row, .unity-console-list-view__item {{ background-color: {ToRgba(row)}; color: {ToRgba(UtilityWindowTheme.CardText)}; }}");
            builder.AppendLine($".CN EntrySelected, .unity-console-row--selected, .unity-console-list-view__item--selected {{ background-color: {ToRgba(selected)}; color: {ToRgba(UtilityWindowTheme.TitleText)}; }}");
            builder.AppendLine($".console-toolbar .unity-toolbar-button, .console-toolbar .unity-toggle, .LogToggle, .Collapse, .ErrorPause, .Clear, .Editor, .unity-console-toolbar .unity-toolbar-button {{ background-color: {ToRgba(WithAlpha(UtilityWindowTheme.Blue, 0.20f))}; color: {ToRgba(UtilityWindowTheme.CardText)}; }}");
        }

        private static void AppendSceneViewCoverageBlock(StringBuilder builder)
        {
            Color strip = WithAlpha(UtilityWindowTheme.HeaderTint, EditorGUIUtility.isProSkin ? 0.84f : 0.24f);
            Color toggle = WithAlpha(UtilityWindowTheme.Blue, EditorGUIUtility.isProSkin ? 0.20f : 0.12f);

            builder.AppendLine("/* Scene view coverage: top/bottom strips, overlay containers, and scene-toolbar toggles where accessible. */");
            builder.AppendLine($".SceneTopBarBg, .SceneViewToolbar, .scene-view-toolbar, .unity-scene-view-toolbar, .unity-scene-view-overlay-strip, .unity-overlay-container, .unity-overlay, .unity-overlay-header {{ background-color: {ToRgba(strip)}; color: {ToRgba(UtilityWindowTheme.TitleText)}; }}");
            builder.AppendLine($".SceneViewToolbar .unity-toolbar-button, .unity-scene-view-toolbar .unity-toolbar-button, .unity-overlay .unity-toolbar-button, .unity-overlay .unity-toggle, .GizmosDropDown, .LayersDropDown, .SceneViewFX, .SceneView2D, .SceneViewAudio {{ background-color: {ToRgba(toggle)}; color: {ToRgba(UtilityWindowTheme.CardText)}; }}");
        }

        private static void AppendTabChromeCoverageBlock(StringBuilder builder)
        {
            Color inactive = WithAlpha(UtilityWindowTheme.HeaderTint, EditorGUIUtility.isProSkin ? 0.72f : 0.18f);
            Color hover = WithAlpha(UtilityWindowTheme.Blue, EditorGUIUtility.isProSkin ? 0.22f : 0.12f);
            Color active = WithAlpha(UtilityWindowTheme.Blue, EditorGUIUtility.isProSkin ? 0.38f : 0.20f);

            builder.AppendLine("/* Dock/tab chrome coverage: active/inactive dock tabs and hover states where the editor exposes tab classes. */");
            builder.AppendLine($".dockHeader, .dragtab, .dragtab-first, .dragtab-last, .unity-tab, .unity-tab__content {{ background-color: {ToRgba(inactive)}; color: {ToRgba(UtilityWindowTheme.TitleText)}; }}");
            builder.AppendLine($".dragtab:hover, .unity-tab:hover, .unity-tab__content:hover {{ background-color: {ToRgba(hover)}; color: {ToRgba(UtilityWindowTheme.TitleText)}; }}");
            builder.AppendLine($".dragtab.active, .dragtab:checked, .unity-tab--active, .unity-tab:checked, .unity-tab__content:checked {{ background-color: {ToRgba(active)}; color: {ToRgba(UtilityWindowTheme.TitleText)}; }}");
        }

        private static void AppendMappedFontBlock(StringBuilder builder, PungentEditorTextTarget target)
        {
            if (!PungentEditorTextRoleMap.GetApplyUss(target))
                return;

            string selectors = PungentEditorTextRoleMap.GetUssSelectors(target);
            if (string.IsNullOrWhiteSpace(selectors))
                return;

            AppendFontBlock(builder, selectors, PungentEditorTextRoleMap.GetTextRole(target));
        }

        private static void AppendFontBlock(StringBuilder builder, string selectors, UtilityWindowTheme.TextRole role)
        {
            string fontUrl = TryGetFontUrl(role.ToString());
            if (string.IsNullOrEmpty(fontUrl))
                return;
            builder.AppendLine($"{selectors} {{ -unity-font: {fontUrl}; }}");
        }

        private static string TryGetFontUrl(string roleName)
        {
            if (!TryParseTextRole(roleName, out UtilityWindowTheme.TextRole role))
                role = UtilityWindowTheme.TextRole.Body;

            Font font = UtilityWindowTheme.GetFont(role);
            if (font == null)
                return string.Empty;

            string assetPath = AssetDatabase.GetAssetPath(font);
            if (string.IsNullOrEmpty(assetPath))
                return string.Empty;

            return $"url(\"project://database/{assetPath}\")";
        }

        private static bool TryParseTextRole(string value, out UtilityWindowTheme.TextRole role)
        {
            if (string.IsNullOrEmpty(value))
            {
                role = UtilityWindowTheme.TextRole.Body;
                return false;
            }

            for (int i = 0; i < System.Enum.GetValues(typeof(UtilityWindowTheme.TextRole)).Length; i++)
            {
                UtilityWindowTheme.TextRole candidate = (UtilityWindowTheme.TextRole)i;
                if (string.Equals(candidate.ToString(), value, System.StringComparison.OrdinalIgnoreCase))
                {
                    role = candidate;
                    return true;
                }
            }

            role = UtilityWindowTheme.TextRole.Body;
            return false;
        }

        private static Color WithAlpha(Color color, float alphaMultiplier)
        {
            color.a = Mathf.Clamp01(color.a * Mathf.Clamp01(alphaMultiplier <= 0f ? 1f : alphaMultiplier));
            return color;
        }

        private static string ToRgba(Color color)
        {
            int r = Mathf.RoundToInt(Mathf.Clamp01(color.r) * 255f);
            int g = Mathf.RoundToInt(Mathf.Clamp01(color.g) * 255f);
            int b = Mathf.RoundToInt(Mathf.Clamp01(color.b) * 255f);
            string a = Mathf.Clamp01(color.a).ToString("0.###", CultureInfo.InvariantCulture);
            return $"rgba({r}, {g}, {b}, {a})";
        }

        private static string EscapeComment(string value)
        {
            return (value ?? string.Empty).Replace("*/", "* /");
        }
    }
#endif
}
