namespace SkiGame.Audio
{
    public enum GameAudioCueId
    {
        None = 0,
        UiOpen = 10,
        UiClose = 11,
        UiClick = 12,
        UiBack = 13,
        UiNavigate = 14,
        UiAdjust = 15,
        UiConfirm = 16,
        UiDeny = 17,
        UiPurchaseSuccess = 18,
        UiPurchaseFail = 19,
        InteractionAccept = 100,
        InteractionCancel = 101,
        InteractionDenied = 102,
        PlayerStack = 200,
        PlayerRecover = 201,
        TrickLand = 220,
        TrickFail = 221,
        LiftQueueJoin = 300,
        LiftQueueLeave = 301,
        LiftAttachChair = 302,
        LiftAttachTBar = 303,
        LiftDetach = 304,
        LiftAccessGranted = 305,
        LiftAccessDenied = 306,
        RaceCountdownTick = 400,
        RaceCountdownGo = 401,
        RaceCheckpoint = 402,
        RaceStart = 403,
        RaceFinish = 404,
        RaceFail = 405,
        RescueStart = 500,
        RescueComplete = 501,
        RescueFail = 502,
        SnowmobileMount = 600,
        SnowmobileDismount = 601,
        ResortEnter = 700,
        ResortExit = 701,
        ShopOpen = 800,
        ShopClose = 801
    }
}
