using System;
using System.Collections.Generic;

namespace PungentFunk.Utilities.Editor.ProjectAudit
{
#if UNITY_EDITOR
    public enum PungentTokenIntentLevel
    {
        NotToken,
        Unlikely,
        Possible,
        Likely,
        Confirmed
    }

    public enum PungentTokenProjectScanMode
    {
        LikelyAuthoredText,
        AllTextAssets,
        StrictOptIn,
        SelectionOnly
    }

    [Serializable]
    public sealed class PungentTokenCandidate
    {
        public string tokenKey = string.Empty;
        public string rawText = string.Empty;
        public string sourceLabel = string.Empty;
        public string sourcePath = string.Empty;
        public string assetGuid = string.Empty;
        public int occurrenceCount;
        public int confidence;
        public PungentTokenIntentLevel intentLevel = PungentTokenIntentLevel.Unlikely;
        public string reason = string.Empty;
        public List<string> reasons = new List<string>();
        public List<string> contexts = new List<string>();
        public bool ignored;
        public bool ignoredByFile;
        public bool ignoredByKey;

        public string Hash
        {
            get
            {
                return PungentTokenParser.NormalizeKey(sourcePath) + "::" + PungentTokenParser.NormalizeKey(tokenKey);
            }
        }
    }

    [Serializable]
    public sealed class PungentTokenScanSettings
    {
        public PungentTokenProjectScanMode projectScanMode = PungentTokenProjectScanMode.LikelyAuthoredText;
        public bool showLikelyCandidates = true;
        public bool showPossibleCandidates = true;
        public bool showUnlikelyCandidates;
        public bool reportLikelyUnknownsAsWarnings = true;
        public bool scanOnlyOptInMarkedFiles;
        public bool ignoreOptOutMarkedFiles = true;
        public int likelyThreshold = 70;
        public int possibleThreshold = 40;
        public List<string> includePathHints = new List<string>
        {
            "Dialogue",
            "Dialog",
            "Localization",
            "Locale",
            "Localisation",
            "Notes",
            "Narrative",
            "Quests",
            "Quest",
            "Content",
            "Text",
            "UI/Text"
        };
        public List<string> excludePathHints = new List<string>
        {
            "Library",
            "Temp",
            "/obj/",
            "/bin/",
            "Packages",
            "package-lock",
            "Generated",
            "AutoGenerated"
        };
        public List<string> ignoredTokenKeys = new List<string>();
        public List<string> ignoredSourcePaths = new List<string>();
        public List<string> ignoredCandidateHashes = new List<string>();

        public void EnsureDefaults()
        {
            if (includePathHints == null)
                includePathHints = new List<string>();
            if (excludePathHints == null)
                excludePathHints = new List<string>();
            if (ignoredTokenKeys == null)
                ignoredTokenKeys = new List<string>();
            if (ignoredSourcePaths == null)
                ignoredSourcePaths = new List<string>();
            if (ignoredCandidateHashes == null)
                ignoredCandidateHashes = new List<string>();

            likelyThreshold = UnityEngine.Mathf.Clamp(likelyThreshold <= 0 ? 70 : likelyThreshold, 1, 100);
            possibleThreshold = UnityEngine.Mathf.Clamp(possibleThreshold <= 0 ? 40 : possibleThreshold, 1, likelyThreshold);
        }
    }
#endif
}
