namespace PungentFunk.Utilities.Editor.Developer.ThemePresetAuthoring
{
#if UNITY_EDITOR && PUNGENTFUNK_INTERNAL_DEVTOOLS
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Text;
    using PungentFunk.Utilities.Editor.Theme;
    using UnityEngine;

    public static class UtilityThemePresetSourceGenerator
    {
        public static string Generate(IEnumerable<UtilityThemePresetSnapshot> snapshots)
        {
            var ordered = snapshots
                .Where(s => s != null)
                .OrderBy(s => (int)s.preset)
                .ToArray();

            var sb = new StringBuilder();
            sb.AppendLine("namespace PungentFunk.Utilities.Editor.Theme");
            sb.AppendLine("{");
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("    using System.Collections.Generic;");
            sb.AppendLine("    using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("    public static partial class UtilityThemePresetLibrary");
            sb.AppendLine("    {");
            sb.AppendLine("        // <auto-generated>");
            sb.AppendLine("        // Generated by PungentFunk Utilities Developer Theme Preset Authoring.");
            sb.AppendLine("        // Do not hand-edit unless you intentionally want to bypass the Appearance workflow.");
            sb.AppendLine("        // </auto-generated>");
            sb.AppendLine("        static partial void BuildGeneratedPresets(List<UtilityThemePresetDefinition> list)");
            sb.AppendLine("        {");

            for (int i = 0; i < ordered.Length; i++)
            {
                AppendSnapshot(sb, ordered[i]);
                sb.AppendLine();
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("#endif");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendSnapshot(StringBuilder sb, UtilityThemePresetSnapshot snapshot)
        {
            sb.AppendLine("            list.Add(new UtilityThemePresetDefinition(");
            sb.AppendLine("                UtilityWindowTheme.ThemePreset." + snapshot.preset + ",");
            sb.AppendLine("                UtilityThemePresetCategory." + snapshot.category + ",");
            sb.AppendLine("                " + Quote(snapshot.displayName) + ",");
            sb.AppendLine("                " + Quote(snapshot.description) + ",");
            sb.AppendLine("                new[] { " + string.Join(", ", (snapshot.tags ?? Array.Empty<string>()).Select(Quote).ToArray()) + " },");
            sb.AppendLine("                UtilityThemePresetTone." + snapshot.tone + ",");
            sb.AppendLine("                UtilityThemePresetColourFamily." + snapshot.colourFamily + ",");
            sb.AppendLine("                new Dictionary<string, Color>");
            sb.AppendLine("                {");

            foreach (KeyValuePair<string, Color> pair in snapshot.colors.OrderBy(p => p.Key, StringComparer.Ordinal))
                sb.AppendLine("                    { UtilityWindowTheme." + RoleConstant(pair.Key) + ", " + ColorLiteral(pair.Value) + " },");

            sb.AppendLine("                },");
            sb.AppendLine("                " + Float(snapshot.panelAlphaDark) + ",");
            sb.AppendLine("                " + Float(snapshot.panelAlphaLight) + ",");
            sb.AppendLine("                " + Float(snapshot.panelBorderOpacity) + ",");
            sb.AppendLine("                " + snapshot.panelBorderWidth + ",");
            sb.AppendLine("                " + snapshot.panelCornerRadius + ",");
            sb.AppendLine("                " + Float(snapshot.density) + ",");
            sb.AppendLine("                " + Bool(snapshot.hiddenFromGallery) + ",");
            sb.AppendLine("                new Dictionary<UtilityWindowTheme.TextRole, string[]>");
            sb.AppendLine("                {");

            foreach (KeyValuePair<UtilityWindowTheme.TextRole, string[]> pair in snapshot.fontHints.OrderBy(p => (int)p.Key))
            {
                string values = string.Join(", ", (pair.Value ?? Array.Empty<string>()).Select(Quote).ToArray());
                sb.AppendLine("                    { UtilityWindowTheme.TextRole." + pair.Key + ", new[] { " + values + " } },");
            }

            sb.AppendLine("                }));");
        }

        private static string RoleConstant(string role)
        {
            switch (role)
            {
                case UtilityWindowTheme.RolePrimary: return nameof(UtilityWindowTheme.RolePrimary);
                case UtilityWindowTheme.RoleSecondary: return nameof(UtilityWindowTheme.RoleSecondary);
                case UtilityWindowTheme.RoleTertiary: return nameof(UtilityWindowTheme.RoleTertiary);
                case UtilityWindowTheme.RoleSuccess: return nameof(UtilityWindowTheme.RoleSuccess);
                case UtilityWindowTheme.RoleWarning: return nameof(UtilityWindowTheme.RoleWarning);
                case UtilityWindowTheme.RoleDanger: return nameof(UtilityWindowTheme.RoleDanger);
                case UtilityWindowTheme.RoleAccentAlt: return nameof(UtilityWindowTheme.RoleAccentAlt);
                case UtilityWindowTheme.RoleNeutral: return nameof(UtilityWindowTheme.RoleNeutral);
                case UtilityWindowTheme.RoleHeader: return nameof(UtilityWindowTheme.RoleHeader);
                case UtilityWindowTheme.RoleTitleText: return nameof(UtilityWindowTheme.RoleTitleText);
                case UtilityWindowTheme.RoleSubtitleText: return nameof(UtilityWindowTheme.RoleSubtitleText);
                case UtilityWindowTheme.RoleMutedText: return nameof(UtilityWindowTheme.RoleMutedText);
                case UtilityWindowTheme.RoleCardText: return nameof(UtilityWindowTheme.RoleCardText);
                case UtilityWindowTheme.RolePathText: return nameof(UtilityWindowTheme.RolePathText);
                case UtilityWindowTheme.RoleLightText: return nameof(UtilityWindowTheme.RoleLightText);
                case UtilityWindowTheme.RoleDarkText: return nameof(UtilityWindowTheme.RoleDarkText);
                case UtilityWindowTheme.RoleResizeHandle: return nameof(UtilityWindowTheme.RoleResizeHandle);
                default: return "\"" + role.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
            }
        }

        private static string ColorLiteral(Color color)
        {
            return "new Color(" + Float(color.r) + ", " + Float(color.g) + ", " + Float(color.b) + ", " + Float(color.a) + ")";
        }

        private static string Float(float value)
        {
            return value.ToString("0.######", CultureInfo.InvariantCulture) + "f";
        }

        private static string Bool(bool value)
        {
            return value ? "true" : "false";
        }

        private static string Quote(string value)
        {
            return "\"" + (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n") + "\"";
        }
    }
#endif
}
